import { emptyDB, nowISO } from "./data";
import type { DB, Role } from "./data";
import { supabase } from "./supabase";

type Row = Record<string, any>;

const rows = async (table: string) => {
  const { data, error } = await supabase.from(table).select("*");
  if (error) throw error;
  return (data ?? []) as Row[];
};
const asNumber = (value: unknown) => Number(value ?? 0);
const by = (items: Row[], key: string) => new Map(items.map((item) => [String(item[key]), item]));

export async function loadRelational(): Promise<DB> {
  const [staff, patients, wards, beds, appointments, vitals, consultations, labTests, labOrders, labResults, medicines, prescriptions, prescriptionItems, admissions, maternity, nursing, invoices, invoiceItems, notifications, audit] = await Promise.all([
    rows("staff"), rows("patients"), rows("wards"), rows("beds"), rows("appointments"), rows("vitals"), rows("consultations"), rows("lab_tests"), rows("lab_orders"), rows("lab_results"), rows("medicines"), rows("prescriptions"), rows("prescription_items"), rows("admissions"), rows("maternity_records"), rows("nursing_notes"), rows("invoices"), rows("invoice_items"), rows("notifications"), rows("audit_logs"),
  ]);
  const patientById = by(patients, "id"); const staffById = by(staff, "id"); const wardById = by(wards, "id"); const bedById = by(beds, "id"); const testById = by(labTests, "id");
  const grouped = (items: Row[], key: string) => { const result = new Map<string, Row[]>(); items.forEach((item) => result.set(item[key], [...(result.get(item[key]) ?? []), item])); return result; };
  const invoiceItemsByInvoice = grouped(invoiceItems, "invoice_id"); const resultsByOrder = grouped(labResults, "lab_order_id"); const itemsByPrescription = grouped(prescriptionItems, "prescription_id"); const notesByAdmission = grouped(nursing.filter((n) => n.admission_id), "admission_id");
  const db = emptyDB();
  db.staff = staff.map((s) => ({ id: s.staff_id, name: s.full_name, role: s.role as Role, dept: s.department, title: s.job_title, phone: s.phone, status: "off-duty", active: s.active, schedule: ["Mon", "Tue", "Wed", "Thu", "Fri"] }));
  db.patients = patients.map((p) => ({ mrn: p.mrn, nationalId: p.national_id, name: p.full_name, dob: p.date_of_birth, gender: p.gender, phone: p.phone, address: p.address, bloodGroup: p.blood_group, allergies: p.allergies ?? [], insurance: p.insurance, nextOfKin: p.next_of_kin ?? { name: "", phone: "", relation: "" }, history: p.history ?? [], medications: p.medications ?? [], registeredAt: p.created_at, status: p.status, financiallyClearedAt: p.financially_cleared_at, financiallyClearedBy: p.financially_cleared_by }));
  db.wards = wards.map((w) => ({ id: w.ward_code, name: w.name, daily: asNumber(w.nightly_charge) }));
  db.beds = beds.map((b) => ({ id: b.bed_code, ward: wardById.get(b.ward_id)?.ward_code ?? "", status: b.status, patientMrn: patientById.get(b.patient_id)?.mrn }));
  db.appointments = appointments.map((a) => ({ id: a.external_id, patientMrn: patientById.get(a.patient_id)?.mrn ?? "", doctorId: staffById.get(a.doctor_id)?.staff_id ?? "", dept: staffById.get(a.doctor_id)?.department ?? "", date: a.appointment_date, time: String(a.appointment_time).slice(0, 5), type: a.appointment_type, reason: a.reason, status: a.status }));
  db.vitalsLog = vitals.map((v) => ({ patientMrn: patientById.get(v.patient_id)?.mrn ?? "", v: { temp: asNumber(v.temperature), bpSys: asNumber(v.bp_systolic), bpDia: asNumber(v.bp_diastolic), pulse: asNumber(v.pulse), resp: asNumber(v.respiration), spo2: asNumber(v.spo2), weight: v.weight == null ? undefined : asNumber(v.weight), height: v.height == null ? undefined : asNumber(v.height), takenAt: v.recorded_at, by: staffById.get(v.recorded_by)?.full_name ?? "" } }));
  db.consultations = consultations.map((c) => ({ id: c.external_id, patientMrn: patientById.get(c.patient_id)?.mrn ?? "", doctorId: staffById.get(c.doctor_id)?.staff_id ?? "", date: c.created_at, complaint: c.complaint, symptoms: c.symptoms ?? [], vitals: c.vitals ?? {}, examination: c.examination, diagnosis: c.diagnosis, treatment: c.treatment, notes: c.notes, followUp: c.follow_up_date ?? undefined, rxId: c.rx_id ?? undefined, labIds: c.lab_ids ?? [] }));
  db.medicines = medicines.map((m) => ({ id: m.medicine_code, name: m.name, category: m.category, batch: m.batch_number, supplier: m.supplier, stock: m.stock, unit: m.unit, buyPrice: asNumber(m.buy_price), sellPrice: asNumber(m.sell_price), expiry: m.expiry_date ?? "", location: m.storage_location, reorderLevel: m.reorder_level }));
  db.labOrders = labOrders.map((o) => ({ id: o.order_no, patientMrn: patientById.get(o.patient_id)?.mrn ?? "", doctorId: staffById.get(o.doctor_id)?.staff_id ?? "", test: testById.get(o.test_id)?.code ?? testById.get(o.test_id)?.name ?? "", priority: o.priority, orderedAt: o.ordered_at, status: o.status, price: asNumber(testById.get(o.test_id)?.actual_price), results: resultsByOrder.get(o.id)?.map((r) => ({ marker: r.marker, value: r.value, unit: r.unit, ref: r.reference_range, flag: r.flag })) ?? [], verifiedBy: staffById.get(o.verified_by)?.staff_id, verifiedAt: o.verified_at, note: o.note }));
  db.rxOrders = prescriptions.map((p) => ({ id: p.prescription_no, patientMrn: patientById.get(p.patient_id)?.mrn ?? "", doctorId: staffById.get(p.doctor_id)?.staff_id ?? "", date: p.prescribed_at, status: p.status, items: itemsByPrescription.get(p.id)?.map((i) => ({ medId: medicines.find((m) => m.id === i.medicine_id)?.medicine_code ?? "", name: i.medicine_name, qty: i.quantity, dose: i.dose, freq: i.frequency, duration: i.duration, unitPrice: asNumber(i.unit_price) })) ?? [], dispensedBy: staffById.get(p.dispensed_by)?.staff_id, dispensedAt: p.dispensed_at }));
  db.admissions = admissions.map((a) => ({ id: a.admission_no, patientMrn: patientById.get(a.patient_id)?.mrn ?? "", bedId: bedById.get(a.bed_id)?.bed_code ?? "", doctorId: staffById.get(a.admitting_doctor_id)?.staff_id ?? "", date: a.admitted_at, diagnosis: a.diagnosis, status: a.status, dischargeDate: a.discharged_at, dailyCharge: asNumber(a.daily_charge), notes: notesByAdmission.get(a.id)?.map((n) => ({ at: n.created_at, by: staffById.get(n.written_by)?.staff_id ?? "", text: n.note })) ?? [] }));
  db.maternityRecords = maternity.map((m) => ({ id: m.record_no, motherMrn: patientById.get(m.mother_id)?.mrn ?? "", createdAt: m.created_at, gravida: m.gravida, parity: m.parity, lmp: m.lmp ?? "", edd: m.edd ?? "", investigations: m.anc_investigations ?? {}, deliveryDate: m.delivery_date ?? "", deliveryOutcome: m.delivery_outcome, deliveryMode: m.delivery_mode, maternalCondition: m.maternal_condition, maternalDischargeDate: m.maternal_discharge_date ?? "", breastfeedingStarted: m.breastfeeding_started, postpartumNotes: m.postpartum_notes, babySex: m.baby_sex, numberOfBabies: String(m.number_of_babies), birthWeight: String(m.birth_weight ?? ""), length: String(m.length_cm ?? ""), headCircumference: String(m.head_circumference_cm ?? ""), apgar1: String(m.apgar_one ?? ""), apgar5: String(m.apgar_five ?? ""), resuscitation: m.resuscitation, complications: m.complications, immunizations: m.immunizations ?? {}, babyConditionAtDischarge: m.baby_condition_at_discharge, nurseNotes: [] }));
  db.invoices = invoices.map((i) => ({ id: i.invoice_no, patientMrn: patientById.get(i.patient_id)?.mrn ?? "", date: i.created_at, items: invoiceItemsByInvoice.get(i.id)?.map((x) => ({ desc: x.description, amount: asNumber(x.amount), kind: x.item_type })) ?? [], paid: asNumber(i.paid), status: i.status }));
  db.notifications = notifications.map((n) => ({ id: n.external_id, at: n.created_at, icon: n.icon, text: n.message, read: !!n.read_at, roles: n.recipient_roles ?? [] }));
  db.audit = audit.map((a) => ({ id: a.external_id, at: a.created_at, user: staffById.get(a.actor_id)?.full_name ?? "System", role: (staffById.get(a.actor_id)?.role ?? "admin") as Role, action: a.action }));
  return db;
}

const upsert = async (table: string, values: Row[], conflict: string) => { if (values.length) { const { error } = await supabase.from(table).upsert(values, { onConflict: conflict }); if (error) throw error; } };
export async function saveRelational(db: DB): Promise<void> {
  await upsert("patients", db.patients.map((p) => ({ mrn: p.mrn, national_id: p.nationalId, full_name: p.name, date_of_birth: p.dob, gender: p.gender, phone: p.phone, address: p.address, blood_group: p.bloodGroup, allergies: p.allergies, insurance: p.insurance, next_of_kin: p.nextOfKin, history: p.history, medications: p.medications, status: p.status, financially_cleared_at: p.financiallyClearedAt ?? null })), "mrn");
  await upsert("wards", db.wards.map((w) => ({ ward_code: w.id, name: w.name, nightly_charge: w.daily })), "ward_code");
  await upsert("medicines", db.medicines.map((m) => ({ medicine_code: m.id, name: m.name, category: m.category, batch_number: m.batch, supplier: m.supplier, stock: m.stock, unit: m.unit, buy_price: m.buyPrice, sell_price: m.sellPrice, expiry_date: m.expiry || null, reorder_level: m.reorderLevel, storage_location: m.location })), "medicine_code");
  const patientRows = await rows("patients"); const staffRows = await rows("staff"); const wardRows = await rows("wards"); const medicineRows = await rows("medicines");
  const patientIds = by(patientRows, "mrn"); const staffIds = by(staffRows, "staff_id"); const staffNames = by(staffRows, "full_name"); const wardIds = by(wardRows, "ward_code"); const medicineIds = by(medicineRows, "medicine_code");
  await Promise.all(db.staff.map(async (s) => { const current = staffIds.get(s.id); if (current) { const { error } = await supabase.from("staff").update({ full_name: s.name, role: s.role, department: s.dept, job_title: s.title, phone: s.phone, active: s.active }).eq("staff_id", s.id); if (error) throw error; } }));
  await upsert("beds", db.beds.map((b) => ({ bed_code: b.id, ward_id: wardIds.get(b.ward)?.id, status: b.status, patient_id: b.patientMrn ? patientIds.get(b.patientMrn)?.id : null })).filter((b) => b.ward_id), "bed_code");
  await upsert("appointments", db.appointments.map((a) => ({ external_id: a.id, patient_id: patientIds.get(a.patientMrn)?.id, doctor_id: staffIds.get(a.doctorId)?.id, appointment_date: a.date, appointment_time: a.time, appointment_type: a.type, reason: a.reason, status: a.status })).filter((a) => a.patient_id && a.doctor_id), "external_id");
  await upsert("vitals", db.vitalsLog.map(({ patientMrn, v }) => ({ external_id: `${patientMrn}:${v.takenAt}:${v.by}`, patient_id: patientIds.get(patientMrn)?.id, recorded_by: (staffIds.get(v.by) ?? staffNames.get(v.by))?.id, temperature: v.temp, bp_systolic: v.bpSys, bp_diastolic: v.bpDia, pulse: v.pulse, respiration: v.resp, spo2: v.spo2, weight: v.weight ?? null, height: v.height ?? null, recorded_at: v.takenAt })).filter((v) => v.patient_id && v.recorded_by), "external_id");
  await upsert("consultations", db.consultations.map((c) => ({ external_id: c.id, patient_id: patientIds.get(c.patientMrn)?.id, doctor_id: staffIds.get(c.doctorId)?.id, complaint: c.complaint, symptoms: c.symptoms, examination: c.examination, diagnosis: c.diagnosis, treatment: c.treatment, notes: c.notes, follow_up_date: c.followUp ?? null, created_at: c.date, vitals: c.vitals, rx_id: c.rxId ?? null, lab_ids: c.labIds })).filter((c) => c.patient_id && c.doctor_id), "external_id");
  const testRows = await rows("lab_tests"); const testIds = by(testRows, "code");
  const testCodes = [...new Set(db.labOrders.map((o) => o.test))];
  await upsert("lab_tests", testCodes.map((code) => ({ code, name: code, category: "General", actual_price: db.labOrders.find((o) => o.test === code)?.price ?? 0 })), "code");
  const refreshedTests = by(await rows("lab_tests"), "code");
  await upsert("lab_orders", db.labOrders.map((o) => ({ order_no: o.id, patient_id: patientIds.get(o.patientMrn)?.id, doctor_id: staffIds.get(o.doctorId)?.id, test_id: (refreshedTests.get(o.test) ?? testIds.get(o.test))?.id, priority: o.priority, status: o.status, note: o.note ?? "", ordered_at: o.orderedAt, verified_by: o.verifiedBy ? staffIds.get(o.verifiedBy)?.id : null, verified_at: o.verifiedAt ?? null })).filter((o) => o.patient_id && o.doctor_id && o.test_id), "order_no");
  const labOrderRows = by(await rows("lab_orders"), "order_no");
  for (const order of db.labOrders) {
    const id = labOrderRows.get(order.id)?.id;
    if (!id) continue;
    await upsert("lab_results", (order.results ?? []).map((result, index) => ({ external_id: `${order.id}:${index}:${result.marker}`, lab_order_id: id, marker: result.marker, value: result.value, unit: result.unit, reference_range: result.ref, flag: result.flag })), "external_id");
  }
  await upsert("prescriptions", db.rxOrders.map((p) => ({ prescription_no: p.id, patient_id: patientIds.get(p.patientMrn)?.id, doctor_id: staffIds.get(p.doctorId)?.id, status: p.status, prescribed_at: p.date, dispensed_by: p.dispensedBy ? staffIds.get(p.dispensedBy)?.id : null, dispensed_at: p.dispensedAt ?? null })).filter((p) => p.patient_id && p.doctor_id), "prescription_no");
  const prescriptionRows = by(await rows("prescriptions"), "prescription_no");
  for (const prescription of db.rxOrders) { const id = prescriptionRows.get(prescription.id)?.id; if (!id) continue; await supabase.from("prescription_items").delete().eq("prescription_id", id); await upsert("prescription_items", prescription.items.map((item) => ({ prescription_id: id, medicine_id: medicineIds.get(item.medId)?.id ?? null, medicine_name: item.name, quantity: item.qty, dose: item.dose, frequency: item.freq, duration: item.duration, unit_price: item.unitPrice })), "id"); }
  const bedRows = await rows("beds"); const bedIds = by(bedRows, "bed_code");
  await upsert("admissions", db.admissions.map((a) => ({ admission_no: a.id, patient_id: patientIds.get(a.patientMrn)?.id, bed_id: bedIds.get(a.bedId)?.id, admitting_doctor_id: staffIds.get(a.doctorId)?.id ?? null, diagnosis: a.diagnosis, status: a.status, admitted_at: a.date, discharged_at: a.dischargeDate ?? null, daily_charge: a.dailyCharge })).filter((a) => a.patient_id && a.bed_id), "admission_no");
  const admissionRows = by(await rows("admissions"), "admission_no");
  for (const admission of db.admissions) {
    const id = admissionRows.get(admission.id)?.id;
    const patientId = patientIds.get(admission.patientMrn)?.id;
    if (!id || !patientId) continue;
    await upsert("nursing_notes", admission.notes.map((note, index) => ({ external_id: `${admission.id}:${index}:${note.at}`, patient_id: patientId, admission_id: id, written_by: (staffIds.get(note.by) ?? staffNames.get(note.by))?.id, note: note.text, created_at: note.at })).filter((note) => note.written_by), "external_id");
  }
  await upsert("invoices", db.invoices.map((i) => ({ invoice_no: i.id, patient_id: patientIds.get(i.patientMrn)?.id, total: i.items.reduce((sum, item) => sum + item.amount, 0), paid: i.paid, status: i.status, created_at: i.date })).filter((i) => i.patient_id), "invoice_no");
  const invoiceRows = by(await rows("invoices"), "invoice_no");
  for (const invoice of db.invoices) { const id = invoiceRows.get(invoice.id)?.id; if (!id) continue; await supabase.from("invoice_items").delete().eq("invoice_id", id); await upsert("invoice_items", invoice.items.map((item) => ({ invoice_id: id, description: item.desc, amount: item.amount, item_type: item.kind })), "id"); }
  await upsert("maternity_records", db.maternityRecords.map((m) => ({ record_no: m.id, mother_id: patientIds.get(m.motherMrn)?.id, gravida: m.gravida, parity: m.parity, lmp: m.lmp || null, edd: m.edd || null, anc_investigations: m.investigations, delivery_date: m.deliveryDate || null, delivery_outcome: m.deliveryOutcome, delivery_mode: m.deliveryMode, maternal_condition: m.maternalCondition, maternal_discharge_date: m.maternalDischargeDate || null, breastfeeding_started: m.breastfeedingStarted, postpartum_notes: m.postpartumNotes, baby_sex: m.babySex, number_of_babies: Number(m.numberOfBabies) || 1, birth_weight: Number(m.birthWeight) || null, length_cm: Number(m.length) || null, head_circumference_cm: Number(m.headCircumference) || null, apgar_one: Number(m.apgar1) || null, apgar_five: Number(m.apgar5) || null, resuscitation: m.resuscitation, complications: m.complications, immunizations: m.immunizations, baby_condition_at_discharge: m.babyConditionAtDischarge })).filter((m) => m.mother_id), "record_no");
  await upsert("notifications", db.notifications.map((n) => ({ external_id: n.id, recipient_roles: n.roles, icon: n.icon, message: n.text, read_at: n.read ? n.at : null, created_at: n.at })), "external_id");
  await upsert("audit_logs", db.audit.map((a) => ({ external_id: a.id, actor_id: (staffIds.get(a.user) ?? staffNames.get(a.user))?.id ?? null, action: a.action, created_at: a.at })), "external_id");
}
